export const featuredCreatives = [
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative1.avif', agency: 'Matthew Marcos', location: 'New Orleans, LA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative2.avif', agency: 'Matthew Marcos', location: 'Atlanta, GA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative3.avif', agency: 'Matthew Marcos', location: 'New Orleans, LA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative4.avif', agency: 'Matthew Marcos', location: 'Seattle, WA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative5.avif', agency: 'Matthew Marcos', location: 'New Orleans, LA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative6.avif', agency: 'Matthew Marcos', location: 'Dallas, TX' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative7.avif', agency: 'Matthew Marcos', location: 'Phoenix, AZ' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative8.avif', agency: 'Matthew Marcos', location: 'Portland, OR' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative9.avif', agency: 'Matthew Marcos', location: 'Boston, MA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative10.avif', agency: 'Matthew Marcos', location: 'Boston, MA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative11.avif', agency: 'Matthew Marcos', location: 'New Orleans, LA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative12.avif', agency: 'Matthew Marcos', location: 'Springfield, IL' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative13.avif', agency: 'Matthew Marcos', location: 'Dallas, TX' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative14.avif', agency: 'Matthew Marcos', location: 'Chicago, IL' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative15.avif', agency: 'Matthew Marcos', location: 'Riverside, CA' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative16.avif', agency: 'Matthew Marcos', location: 'Nashville, TN' },
  // { title: 'Junior Motion Graphics Designer', image: '/creatives/creative16.avif', agency: 'Matthew Marcos', location: 'Boston, MA' },
  // { title: 'Junior Motion Graphics Designer', image: '/creatives/creative16.avif', agency: 'Matthew Marcos', location: 'Boston, MA' },
];