export const featuredCreatives = [
  { title: 'Senior UX User Experience Designer', image: '/creatives/creative1.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative2.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative3.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative4.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative5.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative6.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative7.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative8.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Senior UX User Experience Designer', image: '/creatives/creative9.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Junior Motion Graphics Designer', image: '/creatives/creative10.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative11.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative12.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative13.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative14.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative15.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
  { title: 'Creative Director', image: '/creatives/creative16.avif', agency: 'Matthew Marcos', location: 'NEW YORK, NY' },
];