export const featuredJobs = [
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Detroit, MI' },
  { title: 'coming soon', image: '/jobs/job2.avif', agency: 'AGENCY', location: 'New Orleans, LA' },
  { title: 'coming soon', image: '/jobs/job3.avif', agency: 'AGENCY', location: 'Denver, CO' },
  { title: 'coming soon', image: '/jobs/job4.avif', agency: 'AGENCY', location: 'Chicago, IL' },
  { title: 'coming soon', image: '/jobs/job5.avif', agency: 'AGENCY', location: 'Houston, TX' },
  { title: 'coming soon', image: '/jobs/job6.avif', agency: 'AGENCY', location: 'Detroit, MI' },
  { title: 'coming soon', image: '/jobs/job7.avif', agency: 'AGENCY', location: 'Dallas, TX' },
  { title: 'coming soon', image: '/jobs/job8.avif', agency: 'AGENCY', location: 'Denver, CO' },
];

export const jobsDirectory = [
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Las Vegas, NV' },
  { title: 'coming soon', image: '/jobs/job2.avif', agency: 'AGENCY', location: 'Brooklyn, NY' },
  { title: 'coming soon', image: '/jobs/job3.avif', agency: 'AGENCY', location: 'Houston, TX' },
  { title: 'coming soon', image: '/jobs/job4.avif', agency: 'AGENCY', location: 'Houston, TX' },
  { title: 'coming soon', image: '/jobs/job5.avif', agency: 'AGENCY', location: 'Orlando, FL' },
  { title: 'coming soon', image: '/jobs/job6.avif', agency: 'AGENCY', location: 'Phoenix, AZ' },
  { title: 'coming soon', image: '/jobs/job7.avif', agency: 'AGENCY', location: 'Denver, CO' },
  { title: 'coming soon', image: '/jobs/job8.avif', agency: 'AGENCY', location: 'San Francisco, CA' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Dallas, TX' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Philadelphia, PA' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Dallas, TX' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Seattle, WA' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'New Orleans, LA' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'New Orleans, LA' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Denver, CO' },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL' },
];