export const placeholderFeaturedJobs = [
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Detroit, MI', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'New Orleans, LA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Denver, CO', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Chicago, IL', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Houston, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Detroit, MI', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Dallas, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Denver, CO', item:{} },
];

export const jobsDirectory = [
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Las Vegas, NV', item:{} },
  { title: 'coming soon', image: '/jobs/job2.avif', agency: 'AGENCY', location: 'Brooklyn, NY', item:{} },
  { title: 'coming soon', image: '/jobs/job3.avif', agency: 'AGENCY', location: 'Houston, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job4.avif', agency: 'AGENCY', location: 'Houston, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job5.avif', agency: 'AGENCY', location: 'Orlando, FL', item:{} },
  { title: 'coming soon', image: '/jobs/job6.avif', agency: 'AGENCY', location: 'Phoenix, AZ', item:{} },
  { title: 'coming soon', image: '/jobs/job7.avif', agency: 'AGENCY', location: 'Denver, CO', item:{} },
  { title: 'coming soon', image: '/jobs/job8.avif', agency: 'AGENCY', location: 'San Francisco, CA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Dallas, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Philadelphia, PA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Dallas, TX', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Seattle, WA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'New Orleans, LA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'New Orleans, LA', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Denver, CO', item:{} },
  { title: 'coming soon', image: '/jobs/job1.avif', agency: 'AGENCY', location: 'Orlando, FL', item:{} },
];